name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.Token_Workers }}
          accountId: 30e1abd4edbb7e0f77cd94a5295470e4
